name: flutter_web_file_selector
description: "A Flutter package to let you select files on the Web platform."
version: 0.1.1
homepage: https://github.com/koichia/flutter_web_file_selector

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

platforms:
  web:
